// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1601802766);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1601802886);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1601802526);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1601802646);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1601803006);
user_pref("browser.cache.disk.amount_written", 949);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "IN");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 02 Oct 2020 16:27:06 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1601802766);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"3cb3f785-4559-4de3-8e7b-892743d402f2\",\"default-theme@mozilla.org\":\"9de666cd-bdaa-4f78-8901-87609ca78a6e\",\"google@search.mozilla.org\":\"beaab52a-2506-4600-ab16-3a3eba8be5a6\",\"amazondotcom@search.mozilla.org\":\"8b706b3c-0563-4536-b4e1-13b32d8ebcc0\",\"bing@search.mozilla.org\":\"d10b2ce1-ed21-4ea2-895b-53bcc90569bc\",\"ddg@search.mozilla.org\":\"1c826fc2-b2e3-4be1-acc0-dc3aec526322\",\"twitter@search.mozilla.org\":\"9b9bafc4-8fa5-4afb-b63f-4d2ab7f1a804\",\"wikipedia@search.mozilla.org\":\"814b6aff-8bdc-48cf-892f-5d1f50a14911\"}");
user_pref("idle.lastDailyNotification", 1601802775);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "da486156-6c8e-44d2-98d8-75d27f9238a");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1601802775);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "4cf14d4e-1ef4-4ee8-a309-dde2e8bb67cf");
user_pref("services.blocklist.pinning.checked", 1601803583);
user_pref("services.settings.clock_skew_seconds", -928);
user_pref("services.settings.last_etag", "\"1601798244688\"");
user_pref("services.settings.last_update_seconds", 1601803583);
user_pref("services.settings.main.hijack-blocklists.last_check", 1601803583);
user_pref("services.settings.main.language-dictionaries.last_check", 1601803583);
user_pref("services.settings.main.sites-classification.last_check", 1601803583);
user_pref("services.settings.security.onecrl.checked", 1601803583);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1601802775);
user_pref("toolkit.telemetry.cachedClientID", "83c71fe5-8014-494e-bae1-2afdc261aa06");
user_pref("toolkit.telemetry.prompted", 2);
